
#' 
#' **Weather explains variability in insect biomass, but not its temporal decline**
#'
#' François Duchenne
#' Based on the code provided by 
#' Jörg Müller, Torsten Hothorn, Ye Yuan, Sebastian Seibold, Oliver Mitesser, Julia Rothacher, 
#' Julia Freund, Clara Wild, Marina Wolz, Annette Menzel (revised and resubmitted, 2023)
#'
#' This document reproduces tables and figures.
#'

#'
#' Check for packages and if necessary install into library 
#+ message = FALSE
rm(list=ls())
pkgs <- c("mgcv", "knitr", "multcomp", "coin", "colorspace", "ggplot2", 
          "data.table", "tidyverse", "vegan","sf","gridExtra","scales",
		  "ggeffects","ggforce","raster","viridis","ggnewscale","ggdensity","lme4") 

inst <- pkgs %in% installed.packages()
if (any(inst)) install.packages(pkgs[!inst])
pkg_out <- lapply(pkgs, require, character.only = TRUE)
#' Results were obtained in this environment
date()
sessionInfo()

#' Set working directory
setwd(dir="C:/Users/Duchenne/Documents/Mueller et al Insect Biomass data and R code")
#' The HTML output file was generated by
#library("knitr")
#spin("analysis.R")

#' Estimation method for mgcv::gam(),
#' see https://github.com/DistanceDevelopment/dsm/wiki/Why-is-the-default-smoothing-method-%22REML%22-rather-than-%22GCV.Cp%22%3F
#'
#' Results were compared with both options, results differed marginally
METHOD <- "REML"  ### or "GCV.Cp"
#'

#' Reading all data including published data by Hallmann et al. (2017) PLoS One 12: e0185809 until 2016 (data_org) 
#' and new data collected by our own in 2016, 2019, 2020, 2022 (validation)
data_org <-read.csv2("Data_Update_Revision_spells.csv", header = TRUE)

#' Setup factor coding for year (for plots only)
yr <- as.character(data_org$year)
t16 <- which(yr == "2016" & data_org$dataset == "training")
yr[t16] <- "2016t"
v16 <- which(yr == "2016" & data_org$dataset == "validation")
yr[v16] <- "2016v"
lev <- c(1989:2015, "2016t", "2016v", 2017:2022)
data_org$fyear <- factor(yr, levels = lev, labels = lev)


#FIGURE 1 of the answer:
shp=st_read("NUTS_RG_20M_2021_3035.shp") #available here: https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts#nuts21
shp=subset(shp,LEVL_CODE==0)
shp=st_transform(shp,crs=4326)

margin_map=1

r <- raster("hfp-europe-geo-grid/hfp-europe-geo-grid/hfp_Europe_grid/hfp_europe/hdr.adf") #available here: https://sedac.ciesin.columbia.edu/data/set/wildareas-v2-human-footprint-geographic/data-download
x <- c(xmin=min(data_org$E)-margin_map-1,xmax=max(data_org$E)+margin_map+1)
y <- c(ymin=min(data_org$N)-margin_map-1,ymax=56+1)
xy <- cbind(x,y)
S <- SpatialPoints(xy)
r <- crop(r, extent(bbox(S)), snap="out")
r2=as.data.frame(rasterToPoints(r))

################################################################################################################ FIGURE 1
pl1=ggplot(data=data_org,aes(x=fyear,y=biomass_adj/(todaynr-fromdaynr),fill=dataset))+geom_boxplot()+
theme_bw()+theme(panel.grid=element_blank(),plot.title=element_text(size=14,face="bold",hjust = 0),
legend.position="none",panel.border = element_blank(),axis.line= element_line(),axis.text.x=element_text(angle=90,vjust=0.5))+
ggtitle("a")+
xlab("Years")+ylab("Biomass (g per day)")+
scale_x_discrete(breaks=c(1989:2015, "2016t", "2016v", 2017:2022),drop=F)+
scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),labels = trans_format("log10", math_format(10^.x)))+
scale_color_manual(values=c("#0B4F6C","#CBB9A8"))+scale_fill_manual(values=c("#0B4F6C","#CBB9A8"))

pl2=ggplot()+geom_sf(data=shp)+xlim(c(min(data_org$E)-margin_map,max(data_org$E)+margin_map))+ylim(c(min(data_org$N)-margin_map,56))+
geom_point(data=data_org,aes(x=E,y=N,fill=dataset),color="black",shape=21,alpha=0.4)+
theme_bw()+theme(panel.grid=element_blank(),plot.title=element_text(size=14,face="bold",hjust = 0),
legend.position="none",panel.border = element_blank(),axis.line= element_line(),axis.text.x=element_text(angle=90),
axis.title=element_blank())+
ggtitle("b")+
scale_color_manual(values=c("#0B4F6C","#CBB9A8"))+scale_fill_manual(values=c("#0B4F6C","#CBB9A8"))+coord_sf(expand=F)

pl3=ggplot()+geom_raster(data=r2,aes(x=x,y=y,fill=hfp_europe))+
geom_sf(data=shp,fill=NA,col="black",linewidth=0.7)+
xlim(c(min(data_org$E)-margin_map,max(data_org$E)+margin_map))+ylim(c(min(data_org$N)-margin_map,56))+
scale_fill_gradientn(colors=alpha(c("white","lightyellow","firebrick4","red"),1),name="HFI")+
new_scale_fill()+
#geom_point(data=data_org,aes(x=E,y=N,),color="black",shape=21,fill=NA)+
#geom_hdr(data=data_org,aes(x=E,y=N,color=dataset),probs=c(0.95),fill=NA,linewidth=2)+
scale_fill_manual(values=alpha(c("#0B4F6C","#CBB9A8"),0.1),guide=FALSE)+
scale_colour_manual(values=alpha(c("#0B4F6C","#CBB9A8"),1),guide=FALSE)+
theme_bw()+
theme(panel.grid=element_blank(),plot.title=element_text(size=14,face="bold",hjust = 0),
legend.position="bottom",panel.border = element_blank(),axis.line= element_line(),axis.text.x=element_text(angle=90),
axis.title=element_blank())+
ggtitle("c")+coord_sf(expand=F)

#' Centering the variables precipitation and temperature during sampling on the mean value  
#' (Temp 16.263, Prec 26.87)
#'
#' This allows easier interpretation in the presence of interaction terms
data_org$Tmean_c <- data_org$Tmean -16.263
data_org$Psum_c <- data_org$Psum - 26.87
data_org$year_c <- data_org$year - mean(data_org$year)

#################################################################### TESTING DIFFERENCE BETWEEN TRAINING AND VALIDATION DATASETS
data_org$site=as.factor(data_org$plot)
modeltest_datasets <- gam(biomass ~ s(meandaynr) + offset(log(todaynr - fromdaynr)) + s(E, N, bs = "tp") +
							   s(site,bs="re") +
							   year_c+dataset+
                               Tmean_c * Psum_c + 
                               Tmean_anomaly_april_current * Psum_anomaly_april_current + 
                               Tmean_anomaly_april_prev * Psum_anomaly_april_prev + 
                               Tmean_anomaly_winter * Psum_anomaly_winter + 
                               Tmean_anomaly_meandaynr_prev * Psum_anomaly_meandaynr_prev,
                      family = gaussian(link = "log"), 
                      method = METHOD, 
                      data = data_org)

#PREDICTING average biomass for each  the trend using the mod
newdata=data.frame(meandaynr=mean(data_org$meandaynr),nHerbs=mean(data_org$nHerbs),nTrees =mean(data_org$nTrees ),
Light=mean(data_org$Light),ellenTemperature=mean(data_org$ellenTemperature),Arableland=mean(data_org$Arableland),
Forest=mean(data_org$Forest),
Grassland =mean(data_org$Grassland ),Water=mean(data_org$Water),Tmean_c=mean(data_org$Tmean_c),Psum_c=mean(data_org$Psum_c),
Tmean_anomaly_april_current=mean(data_org$Tmean_anomaly_april_current),
Psum_anomaly_april_current=mean(data_org$Psum_anomaly_april_current),
Tmean_anomaly_april_prev=mean(data_org$Tmean_anomaly_april_prev),Psum_anomaly_april_prev =mean(data_org$Psum_anomaly_april_prev),
Tmean_anomaly_winter=mean(data_org$Tmean_anomaly_winter),Psum_anomaly_winter =mean(data_org$Psum_anomaly_winter),
Tmean_anomaly_meandaynr_prev=mean(data_org$Tmean_anomaly_meandaynr_prev),Psum_anomaly_meandaynr_prev =mean(data_org$Psum_anomaly_meandaynr_prev),
year_c=0,todaynr=10,fromdaynr=0,E=mean(data_org$E),N=mean(data_org$N),dataset=c("training","validation"),site=0)

pre=as.data.frame(predict(modeltest_datasets,type="link",newdata=newdata,se.fit=TRUE,exclude = "s(site)"))
pre$dataset=c("training","validation")

pl4=ggplot(data=pre,aes(x=dataset,y=exp(fit)/10,color=dataset))+geom_pointrange(aes(ymin=exp(fit-1.96*se.fit)/10,ymax=exp(fit+1.96*se.fit)/10))+
theme_bw()+theme(panel.grid=element_blank(),plot.title=element_text(size=14,face="bold",hjust = 0),
legend.position="none",panel.border = element_blank(),axis.line= element_line(),axis.text.x=element_text(angle=0))+
ggtitle("d")+
xlab("")+ylab("Biomass (g per day)")+
scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),labels = trans_format("log10", math_format(10^.x)))+
scale_color_manual(values=c("#0B4F6C","#CBB9A8"))+scale_fill_manual(values=c("#0B4F6C","#CBB9A8"))



pdf("Fig1.pdf",width=9,height=5)
grid.arrange(pl1,pl2,pl3,pl4,layout_matrix=rbind(c(1,2,4),c(1,3,4)),widths=c(2.5,1,1),heights=c(1,1.3))
dev.off();

################################################################################################################ TABLE 1
#' **Splitting in training and validation data**
#'
#' Data published in Hallmann et al. (2017) PLoS One 12: e0185809
dim(training <- subset(data_org, dataset == "training"))
training$year <- as.double(training$year)
training$year_c=training$year-mean(training$year)
#' Own data published partly Uhler et al (2021) Nat Commun. 12(1):5946, 
#' Uhler et al. (2022) Insect Conservation and Diversity 10.1111/icad.12604, 
#' Busse et al. (2022) Insect Conservation and Diversity 10.1111/icad.12592
dim(validation <- subset(data_org, dataset == "validation"))

#' **Generalized additive models** a la Uhler et al (2021) Nat Commun. 12(1):5946.
#' 
#' Model 5 substituting year by anomalies
#'

#' **Model 5:** with weather anomalies instead of year
model5 <- gam(biomass ~ s(meandaynr) + offset(log(todaynr - fromdaynr)) + s(E, N, bs = "tp") +
                               nHerbs + nTrees + Light + ellenTemperature +
                               Arableland + Forest + Grassland + Water + 
                               Tmean_c * Psum_c + 
                               Tmean_anomaly_april_current * Psum_anomaly_april_current + 
                               Tmean_anomaly_april_prev * Psum_anomaly_april_prev + 
                               Tmean_anomaly_winter * Psum_anomaly_winter + 
                               Tmean_anomaly_meandaynr_prev * Psum_anomaly_meandaynr_prev,
                      family = gaussian(link = "log"), 
                      method = METHOD, 
                      data = training)

obj1=summary(model5)
res1=data.frame(Estimate=obj1$p.coeff,se=obj1$se[1:length(obj1$p.coeff)],pval=obj1$p.pv,aic=AIC(model5),resq=obj1$r.sq,varia=names(obj1$p.coeff))
AIC(model5)




#' **New Model:** with weather anomalies AND year
cor(training[,c("year_c","Tmean_c","Psum_c","Tmean_anomaly_april_current","Psum_anomaly_april_current","Tmean_anomaly_april_prev",
"Psum_anomaly_april_prev","Tmean_anomaly_winter","Psum_anomaly_winter","Tmean_anomaly_meandaynr_prev","Psum_anomaly_meandaynr_prev")])

checkmodel=lm(year_c ~ 	Tmean_c * Psum_c + 
						Tmean_anomaly_april_current * Psum_anomaly_april_current + 
						Tmean_anomaly_april_prev * Psum_anomaly_april_prev + 
						Tmean_anomaly_winter * Psum_anomaly_winter + 
						Tmean_anomaly_meandaynr_prev * Psum_anomaly_meandaynr_prev,data=training)
summary(checkmodel)

modelbis <- gam(biomass ~ s(meandaynr) + offset(log(todaynr - fromdaynr)) + s(E, N, bs = "tp") +
                               nHerbs + nTrees + Light + ellenTemperature +
                               Arableland + Forest + Grassland + Water +
							   year_c+
                               Tmean_c * Psum_c + 
                               Tmean_anomaly_april_current * Psum_anomaly_april_current + 
                               Tmean_anomaly_april_prev * Psum_anomaly_april_prev + 
                               Tmean_anomaly_winter * Psum_anomaly_winter + 
                               Tmean_anomaly_meandaynr_prev * Psum_anomaly_meandaynr_prev,
                      family = gaussian(link = "log"), 
                      method = METHOD, 
                      data = training)

obj=summary(modelbis)
res2=data.frame(Estimate=obj$p.coeff,se=obj$se[1:length(obj$p.coeff)],pval=obj$p.pv,aic=AIC(modelbis),resq=obj$r.sq,varia=names(obj$p.coeff))
AIC(modelbis)

#TABLE 1
resf=merge(res1,res2,by="varia",all=T)
resf$varia=factor(resf$varia,levels=c("(Intercept)","nHerbs","nTrees","Light","ellenTemperature","Arableland","Forest","Grassland","Water",
"Tmean_c","Psum_c","Tmean_c:Psum_c",
"Tmean_anomaly_winter","Psum_anomaly_winter","Tmean_anomaly_winter:Psum_anomaly_winter",
"Tmean_anomaly_april_current","Psum_anomaly_april_current","Tmean_anomaly_april_current:Psum_anomaly_april_current",                   
"Tmean_anomaly_april_prev","Psum_anomaly_april_prev","Tmean_anomaly_april_prev:Psum_anomaly_april_prev",
"Tmean_anomaly_meandaynr_prev","Psum_anomaly_meandaynr_prev","Tmean_anomaly_meandaynr_prev:Psum_anomaly_meandaynr_prev"))
resf=resf[order(resf$varia),]
fwrite(resf,"table_1.csv")

####### AIC CHANGE WHEN REMOVING EACH VARIABLE

variables=all.vars(formula(modelbis))[-1]
variables=variables[!(variables %in% c("E", "N", "meandaynr"))]
expla=attr(terms(modelbis), "term.labels")
expla=expla[!(expla %in% c("E", "N", "meandaynr"))]
importf=NULL
for(i in expla){
vartoinclude=expla[grep(i,expla,invert=T,fixed=T)]
formu=as.formula(paste0("biomass~s(meandaynr) + offset(log(todaynr - fromdaynr)) + s(E, N, bs = 'tp')+",paste(vartoinclude,collapse="+")))
modelnew<- gam(formu,family = gaussian(link = "log"), method = METHOD,data = training)
import=data.frame(aic=AIC(modelnew),lik=logLik(modelnew)[1],k=attr(logLik(modelnew),"df"),dev=summary(modelnew)$dev.expl,variable=i)
importf=rbind(importf,import)
plot(aic~as.factor(variable),data=importf)
}

importf=importf[order(importf$aic,decreasing=TRUE),]
importf$variable=factor(importf$variable,levels=importf$variable)
ggplot(data=importf,aes(x=variable,y=aic))+geom_point(stat="identity")+coord_flip()+geom_hline(yintercept=AIC(modelbis))

ggplot(data=importf,aes(x=variable,y=dev))+geom_point(stat="identity")+coord_flip()


################################################################################################################ FIGURE 2

#PREDICTING the trend using the modified model
newdata=data.frame(meandaynr=mean(training$meandaynr),nHerbs=mean(training$nHerbs),nTrees =mean(training$nTrees ),
Light=mean(training$Light),ellenTemperature=mean(training$ellenTemperature),Arableland=mean(training$Arableland),
Forest=mean(training$Forest),
Grassland =mean(training$Grassland ),Water=mean(training$Water),Tmean_c=mean(training$Tmean_c),Psum_c=mean(training$Psum_c),
Tmean_anomaly_april_current=mean(training$Tmean_anomaly_april_current),
Psum_anomaly_april_current=mean(training$Psum_anomaly_april_current),
Tmean_anomaly_april_prev=mean(training$Tmean_anomaly_april_prev),Psum_anomaly_april_prev =mean(training$Psum_anomaly_april_prev),
Tmean_anomaly_winter=mean(training$Tmean_anomaly_winter),Psum_anomaly_winter =mean(training$Psum_anomaly_winter),
Tmean_anomaly_meandaynr_prev=mean(training$Tmean_anomaly_meandaynr_prev),Psum_anomaly_meandaynr_prev =mean(training$Psum_anomaly_meandaynr_prev),
year_c=1989:2016- mean(training$year),todaynr=10,fromdaynr=0,E=mean(training$E),N=mean(training$N))

pre1=as.data.frame(predict(modelbis,type="response",newdata=newdata,se.fit=TRUE))
pre1$dataset2="training"

#compute partial residuals
newdat=training
newdat$year_c=0
training$partial_resid=training$biomass-predict(modelbis,newdata=newdat,type="response")
training$dataset2="training"
#correct the predicts to get partial predicts
pre1$fit=pre1$fit-mean(predict(modelbis,newdata=newdat,type="response"))

#REFITING THE MODEL INCLUDING THE MORE RECENT DATA (VALIDATION DATA) AND PREDICTING
modelbiswithall <- gam(biomass ~ s(meandaynr) + offset(log(todaynr - fromdaynr)) + s(E, N, bs = "tp") +
							   s(site,bs="re") +
							   year_c+
                               Tmean_c * Psum_c + 
                               Tmean_anomaly_april_current * Psum_anomaly_april_current + 
                               Tmean_anomaly_april_prev * Psum_anomaly_april_prev + 
                               Tmean_anomaly_winter * Psum_anomaly_winter + 
                               Tmean_anomaly_meandaynr_prev * Psum_anomaly_meandaynr_prev,
                      family = gaussian(link = "log"), 
                      method = METHOD, 
                      data = data_org)

newdata=data.frame(meandaynr=mean(data_org$meandaynr),nHerbs=mean(data_org$nHerbs),nTrees =mean(data_org$nTrees ),
Light=mean(data_org$Light),ellenTemperature=mean(data_org$ellenTemperature),Arableland=mean(data_org$Arableland),
Forest=mean(data_org$Forest),
Grassland =mean(data_org$Grassland ),Water=mean(data_org$Water),Tmean_c=mean(data_org$Tmean_c),Psum_c=mean(data_org$Psum_c),
Tmean_anomaly_april_current=mean(data_org$Tmean_anomaly_april_current),
Psum_anomaly_april_current=mean(data_org$Psum_anomaly_april_current),
Tmean_anomaly_april_prev=mean(data_org$Tmean_anomaly_april_prev),Psum_anomaly_april_prev =mean(data_org$Psum_anomaly_april_prev),
Tmean_anomaly_winter=mean(data_org$Tmean_anomaly_winter),Psum_anomaly_winter =mean(data_org$Psum_anomaly_winter),
Tmean_anomaly_meandaynr_prev=mean(data_org$Tmean_anomaly_meandaynr_prev),Psum_anomaly_meandaynr_prev =mean(data_org$Psum_anomaly_meandaynr_prev),
year_c=1989:2022-mean(data_org$year),todaynr=10,fromdaynr=0,E=mean(data_org$E),N=mean(data_org$N),site=0)

pre2=as.data.frame(predict(modelbiswithall,type="response",newdata=newdata,se.fit=TRUE))
pre2$dataset2="training+validation"

#compute partial residuals
newdat=data_org
newdat$year_c=0
data_org$partial_resid=data_org$biomass-predict(modelbiswithall,newdata=newdat,type="response",exclude="s(site)")
data_org$dataset2="training+validation"
#correct the predicts to get partial predicts
pre2$fit=pre2$fit-mean(predict(modelbiswithall,type="response",newdata=newdata,exclude="s(site)"))

##### PUT TOGETHER PREDICTIONS
pref=rbind(pre1,pre2)
pref$year=c(1989:2016,1989:2022)

#PLOT PREDICTIONS

pl3=ggplot()+
geom_point(data=training,aes(x=year,y=partial_resid/10),color="#0B4F6C",alpha=0.3)+
geom_point(data=data_org,aes(x=year,y=partial_resid/10),color="#CBB9A8",alpha=0.3)+
geom_ribbon(data=pref,aes(x=year,ymin=fit/10-1.96*se.fit/10,ymax=fit/10+1.96*se.fit/10,fill=dataset2),alpha=0.2)+
geom_line(data=pref,aes(x=year,y=fit/10,color=dataset2),size=1.2)+
theme_bw()+theme(panel.grid=element_blank(),plot.title=element_text(size=14,face="bold",hjust = 0),
legend.position="right",panel.border = element_blank(),axis.line= element_line(),axis.text.x=element_text(angle=0))+
ggtitle("a")+
xlab("Years")+ylab("Partial residuals of biomass (g per day)")+
scale_color_manual(values=c("#0B4F6C","#CBB9A8"))+scale_fill_manual(values=c("#0B4F6C","#CBB9A8"))+
facet_zoom(y=TRUE,ylim =c(10,-10),split = TRUE)+labs(color="dataset used\nto fit the model",fill="dataset used\nto fit the model")

pdf("Fig2.pdf",width=9,height=4)
pl3
dev.off();


#######################################################  ESTIMATE FOR TEMPORAL TREND

newdata=data.frame(meandaynr=mean(training$meandaynr),nHerbs=mean(training$nHerbs),nTrees =mean(training$nTrees ),
Light=mean(training$Light),ellenTemperature=mean(training$ellenTemperature),Arableland=mean(training$Arableland),
Forest=mean(training$Forest),
Grassland =mean(training$Grassland),Water=mean(training$Water),Tmean_c=mean(training$Tmean_c),Psum_c=mean(training$Psum_c),
Tmean_anomaly_april_current=training$Tmean_anomaly_april_current,
Psum_anomaly_april_current=training$Psum_anomaly_april_current,
Tmean_anomaly_april_prev=training$Tmean_anomaly_april_prev,Psum_anomaly_april_prev =training$Psum_anomaly_april_prev,
Tmean_anomaly_winter=training$Tmean_anomaly_winter,Psum_anomaly_winter =training$Psum_anomaly_winter,
Tmean_anomaly_meandaynr_prev=training$Tmean_anomaly_meandaynr_prev,Psum_anomaly_meandaynr_prev=training$Psum_anomaly_meandaynr_prev,
year_c=mean(training$year_c),todaynr=10,fromdaynr=0,E=mean(training$E),N=mean(training$N))

newdata1=cbind(newdata,as.data.frame(predict(modelbis,type="response",newdata=newdata,se.fit=TRUE)))
newdata1$year=training$year

model1=gam(fit ~ year,family = gaussian(link = "log"), method = METHOD, data = newdata1)
b1=as.data.frame(ggpredict(model1,tem="year")$year)

pl4=ggplot()+geom_point(data=newdata1,aes(x=year,y=fit/10),color="hotpink2",alpha=0.1)+
geom_ribbon(data=b1,aes(x=x,ymin=conf.low/10,ymax=conf.high/10),alpha=0.2,fill="hotpink4")+
geom_line(data=b1,aes(x=x,y=predicted/10),size=1.2,col="hotpink4")+theme_bw()+theme(panel.grid=element_blank(),plot.title=element_text(size=14,face="bold",hjust = 0),
legend.position="right",panel.border = element_blank(),axis.line= element_line(),axis.text.x=element_text(angle=0))+
ggtitle("a")+
xlab("Years")+ylab("Biomass predicted by weather conditions only\n(g per day)")

newdata=data.frame(meandaynr=mean(training$meandaynr),nHerbs=training$nHerbs,nTrees =training$nTrees,
Light=mean(training$Light),ellenTemperature=mean(training$ellenTemperature),Arableland=training$Arableland,
Forest=training$Forest,
Grassland =training$Grassland,Water=training$Water,Tmean_c=mean(training$Tmean_c),Psum_c=mean(training$Psum_c),
Tmean_anomaly_april_current=mean(training$Tmean_anomaly_april_current),
Psum_anomaly_april_current=mean(training$Psum_anomaly_april_current),
Tmean_anomaly_april_prev=mean(training$Tmean_anomaly_april_prev),Psum_anomaly_april_prev =mean(training$Psum_anomaly_april_prev),
Tmean_anomaly_winter=mean(training$Tmean_anomaly_winter),Psum_anomaly_winter =mean(training$Psum_anomaly_winter),
Tmean_anomaly_meandaynr_prev=mean(training$Tmean_anomaly_meandaynr_prev),Psum_anomaly_meandaynr_prev =mean(training$Psum_anomaly_meandaynr_prev),
year_c=mean(training$year_c),todaynr=10,fromdaynr=0,E=mean(training$E),N=mean(training$N))

newdata2=cbind(newdata,as.data.frame(predict(model5,type="response",newdata=newdata,se.fit=TRUE)))
newdata2$year=training$year
model2=gam(fit ~ year,family = gaussian(link = "log"), method = METHOD, data = newdata2)
b2=as.data.frame(ggpredict(model2,tem="year")$year)

summary(model2)

pl5=ggplot()+geom_point(data=newdata2,aes(x=year,y=fit/10),color="chartreuse3",alpha=0.1)+
geom_ribbon(data=b2,aes(x=x,ymin=conf.low/10,ymax=conf.high/10),alpha=0.2,fill="chartreuse4")+
geom_line(data=b2,aes(x=x,y=predicted/10),size=1.2,col="chartreuse4")+theme_bw()+theme(panel.grid=element_blank(),plot.title=element_text(size=14,face="bold",hjust = 0),
legend.position="right",panel.border = element_blank(),axis.line= element_line(),axis.text.x=element_text(angle=0))+
ggtitle("b")+
xlab("Years")+ylab("Biomass predicted by habitats conditions only\n(g per day)")


exp(summary(model1)$p.coeff[2]+c(0,-1.96*summary(model1)$se[2],1.96*summary(model1)$se[2]))-1

exp(summary(model2)$p.coeff[2]+c(0,-1.96*summary(model2)$se[2],1.96*summary(model2)$se[2]))-1

plot_grid(pl4,pl5,align="hv",ncol=2)

pdf("Fig3.pdf",width=9,height=4)
plot_grid(pl4,pl5,align="hv",ncol=2)
dev.off();










modelvif <- lm(biomass ~ poly(meandaynr,2) + offset(log(todaynr - fromdaynr)) + nHerbs + nTrees + Light + ellenTemperature +
                               Arableland + Forest + Grassland + Water +
							   year_c+
                               Tmean_c * Psum_c + 
                               Tmean_anomaly_april_current * Psum_anomaly_april_current + 
                               Tmean_anomaly_april_prev * Psum_anomaly_april_prev + 
                               Tmean_anomaly_winter * Psum_anomaly_winter + 
                               Tmean_anomaly_meandaynr_prev * Psum_anomaly_meandaynr_prev,data=training)